# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - release
  - devel
  - oldrel
  - 3.4.2
  - 3.4.0

env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  Rscript -e 'update.packages(ask = FALSE)'
